web:
    build: .
    volumes:
        - .:/code
    links:
        - db
    ports:
        - "40000:4000"

db:
    image: mysql:5.6
    environment:
        MYSQL_USER: reduce
        MYSQL_PASSWORD: reduce
        MYSQL_DATABASE: reduce
        MYSQL_ROOT_PASSWORD: reduce_root

# phpmyadmin:
#     image: corbinu/docker-phpmyadmin
#     links:
#         - db:mysql
#     ports:
#         - "81:80"
#     environment:
#         MYSQL_USERNAME: root
#         MYSQL_PASSWORD: medicine_root
